Arch:
  name: resnet18

Optim:
  name: AdaBound
#  lr: 0.1
#  momentum: 0.9
#  weight_decay: !!float 5e-4

Scheduler:
  name: MultiStepLR
  milestones: [500,1000]
  gamma: 0.1

DataLoader:
  batch_size: 32
  shuffle: true
  num_workers: 16
  drop_last: false

Trainer:
  name: sgd
  max_epoch: 150
  device: cuda
  save_dir: swa/baseline_cifar