Arch:
  name: resnet18

Optim:
  name: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: !!float 5e-4

Scheduler:
  name: MultiStepLR
  milestones: [150,250]
  gamma: 0.1

DataLoader:
  batch_size: 128
  shuffle: true
  num_workers: 16
  drop_last: false

Trainer:
  max_epoch: 350
  device: cuda
  save_dir: swa/baseline_cifar