Arch:
  name: resnet18

Optim:
  name: SGD
  lr: 0.05
  momentum: 0.9
  weight_decay: !!float 5e-4

Scheduler:
  name: CosineAnnealingLR
  alpha_1: 1
  alpha_2: 0.001
  T: 100

DataLoader:
  batch_size: 128
  shuffle: true
  num_workers: 16
  drop_last: false

Trainer:
  max_epoch: 1000
  device: cuda
  save_dir: swa/baseline_cifar