Arch:
  name: dummy
  num_channel: 1
  output_k: 3
  num_sub_heads: 1

Optim:
  name: Adam
  lr: 0.001

Scheduler:
  name: MultiStepLR
  milestones: [10,20,30,40,50,60,70,80,90]
  gamma: 0.5

Trainer:
  save_dir: tmp
  device: cuda


DataLoader:
  batch_size: 3
  shuffle: true
  num_workers: 16
  drop_last: False