Arch:
  name: dummy
  num_channel: 1
  output_k: 10
  num_sub_heads: 1

Optim:
  name: Adam
  lr: 0.0005

Scheduler:
  name: MultiStepLR
  milestones: [100,200,300,400,500,600,700,800,900]
  gamma: 0.7

Trainer:
  max_epoch: 1000
  save_dir: MI_toy_example
  device: cuda


DataLoader:
  batch_size: 40
  shuffle: true
  num_workers: 8
  drop_last: False
